Update 007_passing_files.yaml

diff --git a/.github/workflows/007_passing_files.yaml b/.github/workflows/007_passing_files.yaml
--- a/.github/workflows/007_passing_files.yaml
+++ b/.github/workflows/007_passing_files.yaml
@@ -22,6 +22,14 @@ jobs:
           cd backend
           tox -e unit
           ls -la ${{ github.workspace }}/backend
+          echo "Check specific file:"
+          if [ -f backend/.coverage ]; then
+            echo ".coverage found ✅"
+          else
+            echo "❌ .coverage not found"
+            find . -name ".coverage"
+            exit 1
+          fi
 
       - name: Upload artifact
         uses: actions/upload-artifact@v4
